file(READ "dep_versions.txt" dep_versions)
string(REPLACE "\n" ";" dep_versions ${dep_versions})
foreach(line ${dep_versions})
  if(NOT "${line}" STREQUAL "")
    string(REPLACE "=" ";" line ${line})
    list(GET line 0 _dep)
    list(GET line 1 _ver)
    set(${_dep}_DEFAULT_VERSION ${_ver})
  endif()
endforeach()

message("--->${ASIO_DEFAULT_VERSION}")
message("--->${OPENSSL_DEFAULT_VERSION}")
message("--->${LIBEVENT_DEFAULT_VERSION}")
message("--->${VPP_DEFAULT_VERSION}")
message("--->${LIBCONFIG_DEFAULT_VERSION}")
